require 'rails_best_practices/checks/move_finder_to_named_scope_check'
require 'rails_best_practices/checks/use_model_association_check'
require 'rails_best_practices/checks/use_scope_access_check'
require 'rails_best_practices/checks/add_model_virtual_attribute_check'