# encoding: utf-8
require 'rails_best_practices/core/check'
require 'rails_best_practices/core/runner'
require 'rails_best_practices/core/checking_visitor'
require 'rails_best_practices/core/error'
require 'rails_best_practices/core/nil'
require 'rails_best_practices/core/models'
require 'rails_best_practices/core/model_associations'
require 'rails_best_practices/core/model_attributes'
require 'rails_best_practices/core/mailers'
require 'rails_best_practices/core/methods'
require 'rails_best_practices/core/controllers'

require 'rails_best_practices/core_ext/sexp'
require 'rails_best_practices/core_ext/enumerable'
