# encoding: utf-8
require 'rails_best_practices/core/check'
require 'rails_best_practices/core/configs'
require 'rails_best_practices/core/controllers'
require 'rails_best_practices/core/error'
require 'rails_best_practices/core/gems'
require 'rails_best_practices/core/helpers'
require 'rails_best_practices/core/klasses'
require 'rails_best_practices/core/mailers'
require 'rails_best_practices/core/methods'
require 'rails_best_practices/core/models'
require 'rails_best_practices/core/model_associations'
require 'rails_best_practices/core/model_attributes'
require 'rails_best_practices/core/modules'
require 'rails_best_practices/core/routes'
require 'rails_best_practices/core/runner'
require 'rails_best_practices/core_ext/erubis'
