require 'rails_best_practices/core/core_ext'
require 'rails_best_practices/core/runner'
require 'rails_best_practices/core/checking_visitor'
require 'rails_best_practices/core/error'
require 'rails_best_practices/core/visitable_sexp'